export interface keepData {
    projectIntroTitle:string;
    projectIntroDeploy:string;
    projectIntroExpTitle:string;
    projectIntroExp:string;
    typeScriptMainTitle:string;
    typeScriptTitleOne:string;
    typeScriptTitleOneIntro:string;
    typeScriptTitleTwo:string;
    typeScriptTitleTwoIntro:string;
    typeScriptTitleThr:string;
    typeScriptTitleThrIntro:string;
    reduxTitle:string;
    reduxIntro:string;
    functionIntroTitleOne:string;
    functionIntroOne:string;
    functionIntroTitleTwo:string;
    functionIntroTwo:string;
    functionIntroTitleThr:string;
    functionIntroThr:string;
    functionIntroTitleFour:string;
    functionIntroFour:string;
    functionIntroTitleFive:string;
    functionIntroFive:string;
}